//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubVideo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Permission_Exceptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static Permission_Exceptions defaultInstance = ((Permission_Exceptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Permission_Exceptions())));
        
        public static Permission_Exceptions Default {
            get {
                return defaultInstance;
            }
        }
    }
}
